CREATE DATABASE IF NOT EXISTS wifilan;
CREATE DATABASE IF NOT EXISTS radius;
CREATE DATABASE IF NOT EXISTS smartap_v3;


CREATE USER 'mobileapi'@'%' IDENTIFIED BY '%ui6aV@1w1TIF#';
GRANT ALL PRIVILEGES ON radius.* TO 'mobileapi'@'%' WITH GRANT OPTION;
CREATE USER 'smartap'@'%' IDENTIFIED BY '78704ann';
GRANT ALL PRIVILEGES ON smartap_v3.* TO 'smartap'@'%' WITH GRANT OPTION;
CREATE USER 'wifilan'@'localhost' IDENTIFIED BY '78704ann';
GRANT ALL PRIVILEGES ON *.* TO 'wifilan'@'localhost' WITH GRANT OPTION;




